---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "flexvol.fullname" . }}'
  labels:
    app.kubernetes.io/name: {{ include "flexvol.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "flexvol.chart" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ include "flexvol.fullname" . }}'
  labels:
    app.kubernetes.io/name: {{ include "flexvol.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "flexvol.chart" . }}
rules:
{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
  # Flex plugin needs to run as uid=0 and have access to hostPath to update
  # files on the host
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
    resourceNames: ["privileged"]
{{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: '{{ include "flexvol.fullname" . }}'
  labels:
    app.kubernetes.io/name: {{ include "flexvol.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "flexvol.chart" . }}
subjects:
  - kind: ServiceAccount
    name: '{{ include "flexvol.fullname" . }}'
roleRef:
  kind: Role
  name: '{{ include "flexvol.fullname" . }}'
  apiGroup: rbac.authorization.k8s.io
