---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "recycler.fullname" . }}'
  labels:
    app.kubernetes.io/name: {{ include "recycler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "recycler.chart" . }}


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gluster-subvol:recycler:{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "recycler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "recycler.chart" . }}
rules:
  # Recycler needs to be able to manipulate PVs to mark them available
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["*"]
{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
  # Recycler needs to run as uid=0 to delete files from the PVs
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
    resourceNames: ["anyuid"]
{{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "recycler.fullname" . }}'
  labels:
    app.kubernetes.io/name: {{ include "recycler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "recycler.chart" . }}
subjects:
  - kind: ServiceAccount
    name: '{{ include "recycler.fullname" . }}'
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: gluster-subvol:recycler:{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
