---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "recycler.fullname" . }}'
  labels:
    app.kubernetes.io/name: {{ include "recycler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "recycler.chart" . }}


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gluster-subvol:recycler:{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "recycler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "recycler.chart" . }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "recycler.fullname" . }}'
  labels:
    app.kubernetes.io/name: {{ include "recycler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "recycler.chart" . }}
subjects:
  - kind: ServiceAccount
    name: '{{ include "recycler.fullname" . }}'
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: gluster-subvol:recycler:{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
