apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gluster-subvol-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - rolebindings
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - gluster-subvol.gluster.org
    resources:
      - '*'
    verbs:
      - '*'

---

# The operator needs to be able to create PVs for the Gluster supervols
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gluster-subvol-operator
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - '*'
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - '*'
  # Required in CLusterRole so that PV can have its ownerref set correctly
  - apiGroups:
      - gluster-subvol.gluster.org
    resources:
      - '*'
    verbs:
      - '*'
